spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
app:
    uri: 'http://api.exchangeratesapi.io/v1/'
    secret: dcbebe7649cd482321d410d8c88a3316
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
    operationsSorter: method
  api-docs:
    path: '/api-docs'