spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
app:
    uri: 'https://api.exchangeratesapi.io/v1/'
    secret: dcbebe7649cd482321d410d8c88a3316
#spring:
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#            show_sql: true
#            format_sql: true
#      jdbc:
#        time_zone: UTC
#  datasource:
#    driver-class-name=com: mysql:jdbc:Driver
#    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}